import React from "react"

export const DefaultLayout = React.lazy(() => import("../components/layout/Default"))
export const ProfileLayout = React.lazy(() => import("../components/layout/Profile"))
export const ProfilePreferencesLayout = React.lazy(() => import("../components/layout/ProfilePreferences"))
export const SettingsLayout = React.lazy(() => import("../components/layout/Settings"))

export const Home = React.lazy(() => import("../pages/Home"))
export const About = React.lazy(() => import("../pages/About"))
export const Login = React.lazy(() => import("../pages/Login"))
export const Error = React.lazy(() => import("../pages/Error"))
export const RealTime = React.lazy(() => import("../pages/custom/RealTime"))
export const EstatePerformance = React.lazy(() => import("../pages/custom/EstatePerformance"))
export const StoreAnalytics = React.lazy(() => import("../pages/custom/StoreAnalytics"))
export const ProductAnalysis = React.lazy(() => import("../pages/custom/ProductAnalysis"))
export const Counting = React.lazy(() => import("../pages/sensors/Counting"))
export const AirQuality = React.lazy(() => import("../pages/sensors/AirQuality"))
export const Engagement = React.lazy(() => import("../pages/sensors/Engagement"))
export const VisitorJourney = React.lazy(() => import("../pages/sensors/VisitorJourney"))
export const GeneralSettings = React.lazy(() => import("../pages/settings/GeneralSettings"))
export const Groups = React.lazy(() => import("../pages/settings/Groups"))
export const Profiles = React.lazy(() => import("../pages/settings/Profiles"))
export const RightSystem = React.lazy(() => import("../pages/settings/RightSystem"))
export const Tags = React.lazy(() => import("../pages/settings/Tags"))
export const Users = React.lazy(() => import("../pages/settings/Users"))
export const GeneralProfile = React.lazy(() => import("../pages/profile/GeneralProfile"))
export const Advanced = React.lazy(() => import("../pages/profile/preferences/Advanced"))
export const DateTime = React.lazy(() => import("../pages/profile/preferences/DateTime"))
export const LanguageRegion = React.lazy(() => import("../pages/profile/preferences/LanguageRegion"))
export const Sidebar = React.lazy(() => import("../pages/profile/preferences/Sidebar"))
export const Theme = React.lazy(() => import("../pages/profile/preferences/Theme"))
export const Security = React.lazy(() => import("../pages/profile/Security"))
